### ISSUE TITLE
Erroneous documentation on valid context objects?

### ISSUE THREAD

**Issue by guillaume-algis** [Bertrand/handlebars-objc#11] opened 2014-09-03 09:59 UTC
The page https://github.com/Bertrand/handlebars-objc/blob/master/doc/ContextObjects.md states that

> In most examples you'll find throughout handlebars-objc documentation, context objects are plist-compatible Foundation objects (NSDictionary, NSArray, NSString, NSNumber, etc.).

However, in [HBContextRendering.m, line 45-52](https://github.com/Bertrand/handlebars-objc/blob/master/src/handlebars-objc/context/HBContextRendering.m#L45-L52), `nil` is returned for any class other than `NSString` and `NSNumber`.

My point is, [`NSDate` and `NSData` are valid plist-compatible objects](https://en.wikipedia.org/wiki/Property_list#Mac_OS_X), but are not supported by handlebars-objc. Am I missing something?

**Comment by Bertrand** [comment] 2016-01-20 15:34
Well, obviously the problem is I don't know how to render dates (what locale?) and data (what representation). 

Did you run into this because you were expecting a specific behaviour from the lib, or is just that you think the doc is not as precise as it should be?

**Comment by guillaume-algis** [comment] 2016-01-20 15:41
To be honest, I don't remember what I was expecting at the time.
I _think_ I opened the issue as I thought the doc was misleading, but not 100% sure, sorry :(

**Comment by Bertrand** [comment] 2016-01-20 15:45
ok. I'm closing this issue then as I think the point the doc is trying to make is that context objects are not limited to simple plist-like objects.

**Closed by Bertrand** 2016-01-20 15:45 UTC
